name: production
on:
  push:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: swoole,grpc
    - name: Config composer
      run: composer config --global --auth http-basic.ride-to-the-future.repo.repman.io token 67001fefcf70038c817987b7431f2d17498dc5c2409b4748e51cad87a69b8567
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
#    - name: Execute tests
#      run: php ./vendor/bin/phpunit

  laravel-deploy:
    runs-on: staging
    needs: laravel-tests
    steps:
    - uses: actions/checkout@v2
    - name: Building docker image
      run: |
        shopt -s dotglob
        rm -rf .env
        cp .env.production .env
        sudo docker build -f devops/Dockerfiles/production/Dockerfile-production-api --network=mysql_wo_r2f -t production-mlm-api:1 .
        sudo docker tag production-mlm-api:1 staging-reg.dreamcometrue.ai/production-mlm-api:1
        sudo docker push staging-reg.dreamcometrue.ai/production-mlm-api:1
        sudo docker build -f devops/Dockerfiles/production/Dockerfile-production-roi --network=mysql_wo_r2f -t production-mlm-roi:1 .
        sudo docker tag production-mlm-roi:1 staging-reg.dreamcometrue.ai/production-mlm-roi:1
        sudo docker push staging-reg.dreamcometrue.ai/production-mlm-roi:1
    - name: Redeploy aws containers
      run: |
        sudo /usr/local/bin/aws ecs update-service --cluster dreamcometrue --service mlm-api --enable-execute-command --force-new-deployment
        sudo /usr/local/bin/aws ecs update-service --cluster dreamcometrue --service mlm-roi --enable-execute-command --force-new-deployment

